CREATE DATABASE userData;
use userData;

CREATE TABLE IF NOT EXISTS userTable(
    `id` int AUTO_INCREMENT,
    `username` VARCHAR(100) CHARACTER SET utf8,
    `password` VARCHAR(100) CHARACTER SET utf8,
    `firstname` VARCHAR(100) CHARACTER SET utf8,
    `lastname` VARCHAR(100) CHARACTER SET utf8,
    `email` VARCHAR(100) CHARACTER SET utf8,
    `HomePhone` INT,
    `CellPhone` INT,
    `addy_street` VARCHAR(100) CHARACTER SET utf8,
    `isactivate` BOOLEAN,
    PRIMARY KEY (`id`)
);